parameters:
    allowed_api_keys:
        - '%env(API_KEY)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\ApiTokenAuthenticator:
        arguments:
            $allowedApiKeys: '%allowed_api_keys%'
        tags:
            - { name: 'security.authenticator' }